[versions]

# general
yui = "dev"
lombok = "1.18.38"
spring = "3.4.4"
jda = "5.3.2"

# plugins
shadow = "8.3.6"

[libraries]

# general
yui = { group = "me.whereareiam", name = "Yui", version.ref = "yui" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
spring-boot = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring" }
spring-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "spring" }
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]