[versions]

# general
yui = "dev-562386a"
lombok = "1.18.42"

# testing
spring = "4.0.1"

# plugins
shadow = "9.3.0"
junit-platform = "6.0.1"

[libraries]

# general
yui = { group = "me.whereareiam", name = "Yui", version.ref = "yui" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# testing
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]
